###
GET http://localhost:4000/api/students

###
POST http://localhost:4000/api/students
Content-Type: application/json

{
  "name": "Patrick",
  "surname": "Bateman",
  "email": "patrick.bateman@gmail.com",
  "age": 27,
  "gender":"male"
}


###
POST http://localhost:4000/api/users/signup
Content-Type: application/json

{
  "email": "admin2",
  "password": "@12345"
}

###
GET http://localhost:4000/api/students/643c0bafebdc3637d5682de3

###
DELETE http://localhost:4000/api/students/643c0666ebdc3637d5682ddf

###
PUT http://localhost:4000/api/students/643c0bafebdc3637d5682de3
Content-Type: application/json

{
  "age": 28
}